[cache]
dir = "/tmp/gfpg.AqPOOe/cache"
disk_size_gb = 20.0
memory_size_gb = 2.0

[storage]
url = "file:///tmp/gfpg.AqPOOe/objstore"

[servers.nbd]
addresses = ["127.0.0.1:10809"]
unix_socket = "/tmp/gfpg.AqPOOe/gf.nbd.sock"
api_address = "127.0.0.1:8080"
block_size = 131072
flush_threshold = 500

[[servers.nbd.exports]]
name = "pgdata"
size_gb = 10
transport = "nbd"
compaction_cooldown = 0
