#!/usr/bin/env bash
# Real-config multi-worker validation: the PRODUCT pgbouncer.ini (scram +
# auth_query + TLS + unix_socket_dir empty + so_reuseport=1) run as N workers,
# serving real scram+TLS traffic, with a graceful SIGINT reap of one worker.
#
# This is the piece the unit tests can't cover and the rig only approximated
# (the rig used a trust-auth toy ini). Runs inside the beyond-pg-test Docker
# image (has pgbouncer + postgres). The repo is mounted read-only at /repo so we
# use the ACTUAL committed packer/files/pgbouncer/pgbouncer.ini base.
set -uo pipefail
PGBIN=/usr/lib/postgresql/18/bin
W=/tmp/mwreal
rm -rf "$W"; mkdir -p "$W" /var/run/postgresql
chown -R postgres:postgres "$W" /var/run/postgresql

run_pg() { su postgres -c "$*"; }

# 1. Postgres on :5433 (unix socket), scram password encryption (PG18 default).
run_pg "$PGBIN/initdb -D $W/pg -A trust -U postgres --no-sync" >/dev/null 2>&1
cat >> "$W/pg/postgresql.conf" <<EOF
port = 5433
unix_socket_directories = '/var/run/postgresql'
listen_addresses = '127.0.0.1'
password_encryption = scram-sha-256
EOF
cat > "$W/pg/pg_hba.conf" <<EOF
local all all trust
host  all all 127.0.0.1/32 trust
EOF
run_pg "$PGBIN/pg_ctl -D $W/pg -l $W/pg.log -w start" >/dev/null

# 2. App user with a scram password + a row to read back.
run_pg "$PGBIN/psql -p 5433 -h /var/run/postgresql -U postgres -q" <<'SQL'
CREATE ROLE app LOGIN PASSWORD 'apppass';
CREATE TABLE t(x int);
INSERT INTO t VALUES (42);
GRANT SELECT ON t TO app;
SQL

# 3. The EXACT product pgbouncer auth setup (from supervisor.rs setup_pgbouncer_auth).
run_pg "$PGBIN/psql -p 5433 -h /var/run/postgresql -U postgres -q" <<'SQL'
DO $$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'pgbouncer') THEN
    CREATE ROLE pgbouncer LOGIN PASSWORD NULL;
  END IF;
END $$;
CREATE SCHEMA IF NOT EXISTS pgbouncer;
CREATE OR REPLACE FUNCTION pgbouncer.get_auth(p_user text)
  RETURNS TABLE(username text, password text)
  SECURITY DEFINER LANGUAGE sql AS $$
    SELECT usename::text, passwd::text FROM pg_shadow WHERE usename = p_user
  $$;
GRANT EXECUTE ON FUNCTION pgbouncer.get_auth(text) TO pgbouncer;
-- Schema USAGE — now also emitted by setup_pgbouncer_auth (was missing; without
-- it auth_query fails "permission denied for schema pgbouncer" for every client).
GRANT USAGE ON SCHEMA pgbouncer TO pgbouncer;
SQL

# 4. Ed25519 TLS cert (what beyond-pg self-signs).
openssl req -x509 -newkey ed25519 -days 1 -nodes -keyout "$W/tls.key" -out "$W/tls.crt" -subj /CN=pgb >/dev/null 2>&1
chmod 644 "$W/tls.key" "$W/tls.crt"

# 5. REAL pgbouncer.ini = committed product base + the lines config::pgbouncer_ini appends.
cp /repo/packer/files/pgbouncer/pgbouncer.ini "$W/pgb.ini"
cat >> "$W/pgb.ini" <<EOF

# Pool sizing — generated by beyond-pg from VM resources (4 vCPU).
default_pool_size = 16
max_client_conn = 200
so_reuseport = 1

# TLS — termination for the public 5432 port (generated by beyond-pg).
# pgbouncer 1.25.2 fatals ("failed to load CA: (null)") if a client cert is set
# without client_tls_ca_file. A self-signed cert is its own issuer, so the CA
# points at the cert itself — config::pgbouncer_ini now emits this for self-signed.
client_tls_sslmode = allow
client_tls_cert_file = $W/tls.crt
client_tls_key_file = $W/tls.key
client_tls_ca_file = $W/tls.crt
EOF
chown postgres:postgres "$W/pgb.ini"
echo "=== effective pgbouncer.ini (tail) ==="; tail -16 "$W/pgb.ini"

# 6. Start 3 so_reuseport workers (this is the new behavior: N processes, one port).
for i in 1 2 3; do run_pg "pgbouncer $W/pgb.ini" >/dev/null 2>&1 & done
sleep 2
echo "=== workers alive: $(pgrep -c pgbouncer) (expect 3) ==="

# 7. Drive real scram + TLS traffic through :5432; every query must return 42.
export PGPASSWORD=apppass
CONN="host=127.0.0.1 port=5432 user=app dbname=postgres sslmode=require"
ok=0; fail=0
for i in $(seq 1 90); do
  if [ "$($PGBIN/psql "$CONN" -tAc 'SELECT x FROM t' 2>/dev/null)" = "42" ]; then ok=$((ok+1)); else fail=$((fail+1)); fi
done
echo "=== scram+TLS queries via 3 so_reuseport workers: ok=$ok fail=$fail ==="

# Per-worker CPU — proves traffic actually spread across the workers, not one.
echo "--- per-worker cpu ticks (utime+stime) ---"
for p in $(pgrep pgbouncer); do
  awk -v p="$p" '{u=$14+$15} END{}' "/proc/$p/stat" 2>/dev/null
  printf "  pid %-7s ticks=%s\n" "$p" "$(awk '{s=$0; sub(/^.*\) /,"",s); n=split(s,f," "); print f[12]+f[13]}' /proc/$p/stat 2>/dev/null)"
done

# 8. SIGINT one worker (graceful "safe shutdown"); the rest must keep serving.
VICTIM=$(pgrep pgbouncer | tail -1)
echo "=== SIGINT worker $VICTIM (graceful reap) ==="
kill -INT "$VICTIM"
sleep 2
ok2=0; fail2=0
for i in $(seq 1 60); do
  if [ "$($PGBIN/psql "$CONN" -tAc 'SELECT x FROM t' 2>/dev/null)" = "42" ]; then ok2=$((ok2+1)); else fail2=$((fail2+1)); fi
done
gone=$(kill -0 "$VICTIM" 2>/dev/null && echo NO || echo YES)
echo "=== after reap: workers=$(pgrep -c pgbouncer) victim_gone=$gone queries ok=$ok2 fail=$fail2 ==="

pkill pgbouncer 2>/dev/null
run_pg "$PGBIN/pg_ctl -D $W/pg -m immediate stop" >/dev/null 2>&1
echo DONE
