//! Generates the Beyond-managed `conf.d/` files and embeds the static config
//! files that are written verbatim.
//!
//! The RAM-derived tuning is split across two files with different lifecycles:
//!
//! - `01-tuning.conf` — postmaster-context params (require restart to change):
//!   `shared_buffers`, `max_connections`, `wal_buffers`, `huge_pages`,
//!   `max_worker_processes`, `max_parallel_workers`. Written once at boot.
//!
//! - `02-memory.conf` — sighup/user-context params (take effect on reload):
//!   `effective_cache_size`, `work_mem`, `maintenance_work_mem`,
//!   `max_parallel_workers_per_gather`, `max_parallel_maintenance_workers`.
//!   Written at boot and updated by the memory watcher in `supervisor` when
//!   virtio-mem hotplug changes visible RAM.

use std::io::Write as _;
use std::path::Path;

use crate::pg::PGDATA;

// ---------------------------------------------------------------------------
// Static files (embedded at compile time — must be non-empty before cargo build)
// ---------------------------------------------------------------------------

pub const BEYOND_CONF: &str = include_str!("../packer/files/postgresql/00-beyond.conf");

pub const PG_HBA_CONF: &str = include_str!("../packer/files/postgresql/pg_hba.conf");

pub const PGBOUNCER_INI: &str = include_str!("../packer/files/pgbouncer/pgbouncer.ini");

// ---------------------------------------------------------------------------
// Generated: 01-tuning.conf  (postmaster-context — restart required)
// ---------------------------------------------------------------------------

const PGBOUNCER_POOL_SIZE: u64 = 20; // matches pgbouncer.ini default_pool_size

/// Postmaster-context parameters — require a Postgres restart to take effect.
/// Written once at boot; not touched by the memory watcher.
pub fn tuning_conf_boot(ram_bytes: u64, vcpus: u32) -> String {
    let ram_mb = ram_bytes / (1024 * 1024);
    let vcpus = vcpus as u64;

    // max_connections: PgBouncer pool + direct-path headroom + reserved slots.
    // Components: pool_size (PgBouncer server connections) + vcpus*2 (optimal
    // active connections for SSD per empirical formula cores*2+spindles, spindles≈0)
    // + 10 reserved (superuser, monitoring, pg_dump).
    // Floor 100 so tiny VMs leave room for ETL on the direct :5433 path.
    // Ceiling ram_mb/50 (~10 MB/connection overhead) prevents OOM.
    // Ref: PostgreSQL wiki "Number Of Database Connections"; Mattermost PgBouncer study
    let max_connections = (PGBOUNCER_POOL_SIZE + vcpus * 2 + 10).clamp(100, (ram_mb / 50).max(100));

    // shared_buffers: 25% of RAM, floor 128MB.
    // Ref: PostgreSQL docs §20.4; pganalyze shared_buffers benchmark (2024) —
    // 25% is optimal up to ~64 GB; gains plateau above 40% due to double-buffering.
    let shared_buffers_mb = (ram_mb / 4).max(128);

    // wal_buffers: replicates Postgres auto-tune (wal_buffers=-1 = shared_buffers/32).
    // 16 MB ceiling is the historical single-WAL-segment size and is sufficient for
    // typical OLTP. High-concurrency write workloads may benefit from 64 MB.
    // Ref: EDB "Tuning shared_buffers and wal_buffers"
    let wal_buffers_mb = (shared_buffers_mb / 32).clamp(1, 16);

    // vCPU-derived parallelism.
    // max_worker_processes: vcpus + 4 to leave slots for non-parallel background
    // workers (autovacuum launcher, archiver, WAL senders). vcpus*2 has no empirical
    // basis and wastes process-table slots.
    // max_parallel_workers: equal to vCPU count — setting above vCPU count causes
    // context-switch overhead with no throughput gain.
    // Ref: Crunchy Data "Parallel Queries in Postgres"; jamesguthrie.ch PG parallel benchmark
    let max_worker_processes = (vcpus + 4).max(8);
    let max_parallel_workers = vcpus.max(1);

    format!(
        "# Generated by beyond-pg at boot from VM resources. Do not edit.\n\
         # Regenerated on every boot so resized VMs pick up correct values.\n\
         \n\
         # RAM-derived\n\
         shared_buffers = {shared_buffers_mb}MB\n\
         max_connections = {max_connections}\n\
         wal_buffers = {wal_buffers_mb}MB\n\
         # huge_pages=on requires nr_hugepages to be reserved before postgres starts;\n\
         # apply_kernel_settings() does this earlier in do_boot().\n\
         # Ref: Percona \"Benchmark PostgreSQL with Linux HugePages\";\n\
         #      PostgreSQL docs §19.4\n\
         huge_pages = on\n\
         \n\
         # vCPU-derived\n\
         max_worker_processes = {max_worker_processes}\n\
         max_parallel_workers = {max_parallel_workers}\n"
    )
}

// ---------------------------------------------------------------------------
// Generated: 02-memory.conf  (reload-safe — pg_reload_conf() suffices)
// ---------------------------------------------------------------------------

/// Reload-safe parameters — take effect via `pg_reload_conf()` without restart.
/// Written at boot and updated live by the memory watcher in `supervisor` when
/// virtio-mem hotplug changes the amount of visible RAM.
pub fn tuning_conf_adaptive(ram_bytes: u64, vcpus: u32) -> String {
    let ram_mb = ram_bytes / (1024 * 1024);
    let vcpus = vcpus as u64;

    // effective_cache_size: 75% of RAM (shared_buffers + OS page cache estimate).
    // Planner hint only — no memory allocated. 75% is the consensus value for a
    // dedicated server where the OS retains the rest.
    // Ref: PostgreSQL wiki; CYBERTEC "effective_cache_size explained"
    let effective_cache_mb = ram_mb * 3 / 4;

    // maintenance_work_mem: 5% of RAM, cap 2GB.
    // 2 GB cap prevents autovacuum (default 3 workers) from consuming 6 GB.
    // Note: autovacuum workers are internally capped at 1 GB regardless of this
    // setting; the cap mainly governs manual VACUUM and CREATE INDEX.
    // Ref: Robert Haas "How Much maintenance_work_mem Do I Need?" (2019)
    let maintenance_work_mb = (ram_mb / 20).min(2048);

    // work_mem: half of RAM divided by (pool_size × avg sort/hash nodes per plan).
    // work_mem is per sort/hash *node*, not per connection — a query with 3 sorts
    // uses 3×work_mem. Avg 3 nodes/plan is the empirically observed baseline for
    // OLTP with analytical extensions (pgvector ANN, postgis, pg_search).
    // Floor 32MB so even tiny VMs get something useful for ANN searches.
    // Tune empirically: raise log_temp_files threshold and monitor spills.
    // Ref: pganalyze "The surprising logic of Postgres work_mem" (2024)
    let work_mem_mb = (ram_mb / 2 / (PGBOUNCER_POOL_SIZE * 3)).max(32);

    // max_parallel_*_per_gather: vcpus/2 with ceiling 4 for OLTP safety; benchmarks
    // show gains up to ~8 workers on large tables before diminishing returns.
    // Ref: Crunchy Data "Parallel Queries in Postgres"; jamesguthrie.ch PG parallel benchmark
    let max_parallel_workers_per_gather = (vcpus / 2).clamp(1, 4);
    let max_parallel_maintenance_workers = (vcpus / 2).clamp(1, 4);

    format!(
        "# Generated by beyond-pg. Updated at boot and on virtio-mem hotplug.\n\
         # Safe to reload without restarting postgres (pg_reload_conf()).\n\
         \n\
         # RAM-derived (reload-safe)\n\
         effective_cache_size = {effective_cache_mb}MB\n\
         maintenance_work_mem = {maintenance_work_mb}MB\n\
         work_mem = {work_mem_mb}MB\n\
         \n\
         # vCPU-derived (reload-safe)\n\
         max_parallel_workers_per_gather = {max_parallel_workers_per_gather}\n\
         max_parallel_maintenance_workers = {max_parallel_maintenance_workers}\n"
    )
}

// ---------------------------------------------------------------------------
// Generated: 02-durability.conf (ephemeral mode)
// ---------------------------------------------------------------------------

pub const DURABILITY_CONF_EPHEMERAL: &str = "# Generated by beyond-pg. Present only on ephemeral volumes.\n\
     # synchronous_commit=off gives 5-10x faster commits; ~10ms data-loss\n\
     # window on crash is irrelevant on a throwaway volume.\n\
     synchronous_commit = off\n";

// ---------------------------------------------------------------------------
// Atomic write helper
// ---------------------------------------------------------------------------

/// Write `content` to `path` atomically using a temp file and rename.
/// Both paths must be on the same filesystem (always true here: both
/// are under PGDATA or /etc on the same volume).
pub fn write_atomic(path: &Path, content: &str) -> std::io::Result<()> {
    write_atomic_bytes(path, content.as_bytes())
}

/// Binary variant of [`write_atomic`].
pub fn write_atomic_bytes(path: &Path, content: &[u8]) -> std::io::Result<()> {
    let dir = path.parent().unwrap_or(Path::new("."));
    let mut tmp = tempfile::Builder::new().prefix(".tmp.").tempfile_in(dir)?;
    tmp.write_all(content)?;
    tmp.flush()?;
    let tmp_path = tmp.into_temp_path();
    tmp_path.persist(path).map_err(|e| e.error)
}

// ---------------------------------------------------------------------------
// Well-known paths
// ---------------------------------------------------------------------------

pub fn conf_d_dir() -> String {
    format!("{PGDATA}/conf.d")
}

/// Path to the primary PostgreSQL config file (replaces the initdb default).
///
/// BEYOND_CONF contains `include_dir = 'conf.d'` at the end, so all
/// conf.d/*.conf files (tuning, durability) are picked up from there.
/// Writing to postgresql.conf directly (not conf.d/) avoids circular includes.
pub fn beyond_conf_path() -> String {
    format!("{}/postgresql.conf", PGDATA)
}

pub fn tuning_conf_path() -> String {
    format!("{}/conf.d/01-tuning.conf", PGDATA)
}

pub fn memory_conf_path() -> String {
    format!("{}/conf.d/02-memory.conf", PGDATA)
}

pub fn durability_conf_path() -> String {
    format!("{}/conf.d/03-durability.conf", PGDATA)
}

pub fn wal_sink_conf_path() -> String {
    format!("{}/conf.d/03-wal-sink.conf", PGDATA)
}

pub fn wal_sink_conf() -> String {
    "# Generated by beyond-pg when BEYOND_PG_WAL_SINK is set.\n\
     # Commits wait for WAL acknowledgment from the WAL sink before returning.\n\
     synchronous_commit = remote_write\n\
     synchronous_standby_names = 'wal_sink'\n"
        .to_string()
}

pub const PG_HBA_PATH: &str = "/etc/postgresql/18/main/pg_hba.conf";
pub const PGBOUNCER_INI_PATH: &str = "/etc/pgbouncer/pgbouncer.ini";
pub const SYSCTL_PATH: &str = "/etc/sysctl.d/99-postgres.conf";
pub const THP_PATH: &str = "/sys/kernel/mm/transparent_hugepage/enabled";

pub const SYSCTL_CONF: &str = "\
# vm.swappiness: reduce kernel tendency to swap anonymous pages (e.g. work_mem)
# under moderate memory pressure. Value 10 avoids paging hot database memory
# while leaving the OOM killer a pressure valve.
# Ref: Red Hat PostgreSQL tuning guide; Percona \"Out of Memory Killer\" post
vm.swappiness = 10

# vm.overcommit_memory=2: kernel refuses allocations that exceed CommitLimit
# instead of killing processes after the fact. Postmaster survives; the failing
# client gets ENOMEM instead of a cluster restart.
# vm.overcommit_ratio=80: CommitLimit = (80% * RAM) + swap. Default 50 is too
# tight once shared_buffers (25% RAM) + workers are counted on a dedicated host.
# Ref: PostgreSQL docs §19.4; Cybertec \"Memory Overcommit and PostgreSQL\"
vm.overcommit_memory = 2
vm.overcommit_ratio = 80

# vm.dirty_*_bytes: fix-byte writeback thresholds instead of ratio-based defaults.
# On large-RAM hosts, dirty_background_ratio=10% allows multi-GB dirty backlogs
# before flush starts, causing multi-second I/O stalls timed to checkpoints.
# Tradeoff: ~11-14% TPS reduction and ~50-70% slower vacuum on write-heavy
# workloads — test on your storage before adjusting further.
# Ref: Greg Smith / EDB \"Tuning Linux for Low PostgreSQL Latency\";
#      PostgreSQL mailing list 2010-04-12 (id 4BC796EF.5030902@2ndquadrant.com)
vm.dirty_background_bytes = 67108864
vm.dirty_bytes = 536870912

# vm.min_free_kbytes: kernel page reserve for atomic allocations. Too low and
# the OOM killer fires even when memory is technically available.
# 128 MB is a safe floor for large-RAM hosts.
vm.min_free_kbytes = 131072

# kernel.sched_migration_cost_ns: time the CFS scheduler treats a process as
# \"cache hot\" after migration, resisting re-migration. Default 500µs is far too
# short under a large process table — the scheduler thrashes backends across
# cores, burning system CPU. 5 ms stabilises placement.
# Measured: 5x TPS improvement at 900 connections (20% → 70% sys CPU reversed).
# Ref: Shaun Thomas, pgsql-performance 2012-12-31 (id 50E4AAB1.9040902@optionshouse.com);
#      confirmed on LKML (lkml.iu.edu/hypermail/linux/kernel/1507.1/00767.html)
kernel.sched_migration_cost_ns = 5000000

# kernel.sched_autogroup_enabled: groups tasks by TTY for desktop responsiveness,
# which starves long-running server daemons of CPU time. No benefit on a
# headless VM; disabling gives a standalone ~30% TPS boost.
# Ref: same Shaun Thomas benchmark above
kernel.sched_autogroup_enabled = 0

# net.core.somaxconn: kernel listen-backlog cap for TCP sockets. PostgreSQL's
# own listen_backlog is silently clamped to this. PgBouncer absorbs most
# connection pressure, but raising this prevents drops during restart storms.
# Ref: PostgreSQL docs §19.3; Red Hat RHEL PostgreSQL tuning profile
net.core.somaxconn = 1024

# fs.aio-max-nr: system-wide cap on in-flight async I/O requests.
# Required for PostgreSQL 18+ io_method=io_uring; exhausting the default (65536)
# causes allocation failures under high concurrency with direct I/O.
# Ref: pganalyze \"PostgreSQL 18 Async I/O Explainer\"; Red Hat tuning profile
fs.aio-max-nr = 1048576

# net.ipv4.tcp_syn_retries: SYN retransmit attempts before giving up on a new
# connection. Default 6 (~127s total). Value 2 (~7s) cuts connection setup
# latency when a peer is unreachable — acceptable on a private overlay network
# where packet loss is rare and fast failure is preferred.
net.ipv4.tcp_syn_retries = 2
";
