name: beyond-pg-sink build
on:
  push:
    paths:
      - 'beyond-pg-sink/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
  pull_request:
    paths:
      - 'beyond-pg-sink/**'
      - 'Cargo.toml'
      - 'Cargo.lock'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
      - name: Install system dependencies
        run: sudo apt-get install -y libreadline-dev uuid-dev
      - uses: jdx/mise-action@v4
      - name: Cross-compile for Linux amd64
        run: cross build --release -p beyond-pg-sink --target x86_64-unknown-linux-gnu
      - name: Cross-compile for Linux arm64
        run: cross build --release -p beyond-pg-sink --target aarch64-unknown-linux-gnu
      - name: Upload binaries
        uses: actions/upload-artifact@v7
        with:
          name: beyond-pg-sink-${{ github.sha }}
          path: |
            target/x86_64-unknown-linux-gnu/release/beyond-pg-sink
            target/aarch64-unknown-linux-gnu/release/beyond-pg-sink
          retention-days: 14
